### ISSUE TITLE
【办公自动化】--流程历史，界面显示应该调整，按照下图，因为用户根本不关心主键和流程定义代码

### ISSUE THREAD

**Issue by jixuelian** [chenyanxu/kalix-parent#118]
![20160919](https://cloud.githubusercontent.com/assets/7627456/18624218/5dafae56-7e78-11e6-8f2d-b2baeefa6687.PNG)

**Comment by minikiller** [comment]
该功能是面对系统管理员，用户默认情况下是不需要查看该页面的。已经修改了查询条件。
