### ISSUE TITLE
【新闻公告】--公司公告--查询问题

### ISSUE THREAD

**Issue by 576226387** [chenyanxu/kalix-parent#138]
问题：1. 输入标题内容后，点击查询，查询失败
          2.  执行查询操作后，没有任何按钮使页面恢复到未查询之前的状态，建议加入该功能
![3](https://cloud.githubusercontent.com/assets/22948974/19548678/8423df72-96d2-11e6-8407-a6ef8916be18.png)

**Comment by minikiller** [comment]
1.默认是完全匹配查询，已经修改成模糊查询；
2.重置按钮可以恢复未查询状态
