### ISSUE TITLE
【消息通知】--收件箱--发件--收件人--问题：收件人里面没有“管理员”用户

### ISSUE THREAD

**Issue by 576226387** [chenyanxu/kalix-parent#150]
![10](https://cloud.githubusercontent.com/assets/22948974/19588669/e38d4ce2-9799-11e6-80eb-3a03419e29ef.png)

**Comment by minikiller** [comment]
需要搜索管理员，admin是登录名，管理员是用户名，默认搜索是按照用户名的。
