### ISSUE TITLE
【权限管理】--用户管理--添加

### ISSUE THREAD

**Issue by 576226387** [chenyanxu/kalix-parent#152]
问题：1. ”性别”为输入框，建议“性别”处加入下拉列表，里面属性为“男”“女”
           2. 工号默认为0. 建议：该输入框设为空或系统根据人员信息自动排序
           3. 当未输入任何信息，点击“保存”，提示框弹出的信息为“密码不能为空”。建议：不弹出提示框，将所有的必填项输入框设为红色。

**Comment by paning** [comment]
1.已修改为下拉别表
2.暂不修改
3.不弹出对话框了，改为红色框提示
