### ISSUE TITLE
【权限管理】--工作组管理--添加--只输入名称，其他必填项未填写--问题：没有任何提示，且保存成功

### ISSUE THREAD

**Issue by 576226387** [chenyanxu/kalix-parent#156]
![11](https://cloud.githubusercontent.com/assets/22948974/19676231/8d0e054e-9ac5-11e6-9a53-4b686d4bfc3d.png)

**Comment by paning** [comment]
增加工作组必填项的校验功能

**Comment by 576226387** [comment]
复测未通过
操作步骤：1. 输入”名称”和”所属应用”内容
                 2. 删除“名称”内的内容
                 3. 点击“保存”
问题：仍可成功保存

**Comment by qingjie1201** [comment]
已经修改
