### ISSUE TITLE
【权限管理】--角色管理、工作组管理--添加用户--在“姓名内“输入字符后，点击保存，提示：“未修改”。建议：点击“保存”后，没有任何提示，关闭对话框

### ISSUE THREAD

**Issue by 576226387** [chenyanxu/kalix-parent#159]
![13](https://cloud.githubusercontent.com/assets/22948974/19676765/9db9ee50-9ac8-11e6-8d1e-4d307cbed0dc.png)

**Comment by qingjie1201** [comment]
修改完成，提示信息应该保留，提示“信息未变化”
