### ISSUE TITLE
【权限管理】--用户管理--添加

### ISSUE THREAD

**Issue by 576226387** [chenyanxu/kalix-parent#160]
问题：登录名输入框，当输入已经存在的登录名后，没有任何提示
建议：对于已经存在的登录名，当再次添加时，应提示“该名称已经存在”

**Comment by qingjie1201** [comment]
修改完成

**Comment by 576226387** [comment]
复测未通过
只输入已经存在的用户名，点击“保存”，系统只是对必填项进行提示，未提示已经存在的用户名

**Comment by qingjie1201** [comment]
修改完成，登录名增加即时校验，即输入登录名后失去焦点判断登录名是否存在
