### ISSUE TITLE
【权限管理】--角色管理--添加

### ISSUE THREAD

**Issue by 576226387** [chenyanxu/kalix-parent#161]
问题：当添加存在的角色名称时，提示信息为“角色已经存在”，提示信息的内容与添加框内的属性名称不一致。
建议，将名称进行统一
![14](https://cloud.githubusercontent.com/assets/22948974/19753324/41f0098c-9c36-11e6-8c66-7b264cfffea2.png)

**Comment by qingjie1201** [comment]
修改完成
