### ISSUE TITLE
【组织机构】--机构管理--编辑

### ISSUE THREAD

**Issue by 576226387** [chenyanxu/kalix-parent#166]
问题：编辑完信息后，点击“保存”，编辑对话框没有消失

![16](https://cloud.githubusercontent.com/assets/22948974/19756913/6215ee9a-9c52-11e6-9cee-c5503cf36a8f.png)

**Comment by paning** [comment]
已修复

**Comment by 576226387** [comment]
复测没有通过，对话框仍然没有关闭

**Comment by qingjie1201** [comment]
测试没问题
