### ISSUE TITLE
重复登录报错

### ISSUE THREAD

**Issue by chenyanxu** [chenyanxu/kalix-parent#17]
重复登录系统报错，无法继续进入系统，需要显示调用logout才可以

**Comment by chenyanxu** [comment]
[https://github.com/chenyanxu/kalix-parent/commit/acdd798fd3bb1c02d7734d80f482e9300c8a53cf](url)

**Comment by chenyanxu** [comment]
[会根据换句话](https://github.com/chenyanxu/kalix-parent/commit/acdd798fd3bb1c02d7734d80f482e9300c8a53cf)

**Comment by qingjie1201** [comment]
已经解决
