### ISSUE TITLE
应用管理--将“添加、编辑、删除”功能去掉。

### ISSUE THREAD

**Issue by 576226387** [chenyanxu/kalix-parent#178]

**Comment by qingjie1201** [comment]
修改完成，将应用管理里应用列表中系统应用操作的停止、编辑、删除功能屏蔽掉，其它的添加、编辑、删除功能不能去掉。

**Comment by qingjie1201** [comment]
修改完成，将应用管理里应用列表中系统应用操作的停止、编辑、删除功能屏蔽掉，其它的添加、编辑、删除功能不能去掉。
