### ISSUE TITLE
权限管理--用户管理--编辑--问题：当非必填项“电话号”为空时，单击“保存”，提示“填入必填项”

### ISSUE THREAD

**Issue by 576226387** [chenyanxu/kalix-parent#194]
![23](https://cloud.githubusercontent.com/assets/22948974/20206732/6d157fbe-a81d-11e6-8c7e-f6f77216eaac.png)

**Comment by qingjie1201** [comment]
修改完成，提示信息错误，提示信息修改成‘信息未变化’
