### ISSUE TITLE
分离应用的初始化代码到各个应用中

### ISSUE THREAD

**Issue by minikiller** [chenyanxu/kalix-parent#21]
目前应用的初始化代码集中在command中，应该分离到应用中，在应用的核心模块加载时候，初始化数据库。

**Comment by chenyanxu** [comment]
在chenyanxu/tools-parent的tools-karaf-command模块里，通过kalix:init-db命令实现。
根据当前运行的app，动态运行sql文件。参见[readme](https://github.com/chenyanxu/tools-parent/tree/master/tools-karaf-command)说明
