### ISSUE TITLE
消息通知--收件箱/发件箱--问题：点击任意属性，属性列表前面的方框都会被选中，再次点击属性值，方框选中被取消

### ISSUE THREAD

**Issue by 576226387** [chenyanxu/kalix-parent#211]
![26](https://cloud.githubusercontent.com/assets/22948974/20295143/2e1a5342-ab3e-11e6-9866-a320327653b9.png)

**Comment by minikiller** [comment]
这是对的，支持多选删除操作。

**Comment by 576226387** [comment]
OK
