### ISSUE TITLE
布置任务--查看任务--关闭--问题：弹出“要保存修改吗？”对话框

### ISSUE THREAD

**Issue by 576226387** [chenyanxu/kalix-parent#218]
建议：1. 无论是添加还是查看功能，将该对话框弹出。目前该对话框弹出的很任性
![30](https://cloud.githubusercontent.com/assets/22948974/20336382/91633d26-ac04-11e6-906a-a17dc3ff9277.png)

**Comment by zangyanming** [comment]
请更新至最新程序
