### ISSUE TITLE
动态创建app，module，以及menu，button的服务

### ISSUE THREAD

**Issue by minikiller** [chenyanxu/kalix-parent#23]
目前这些服务都是手工创建，不但增加了bundle的数量还需要人工创建代码，现在已经把这些转移到了configAdmin管理了。
可以利用osgi delegation模块的功能，自动创建服务，减少代码编写。

**Comment by chenyanxu** [comment]
[Modify Ant Plugin to auto deploy etc files](https://github.com/chenyanxu/kalix-parent/commit/1ac13d87068ce3735ec6be7d6b434a97655b1433)

**Comment by chenyanxu** [comment]
[admin-parent :Add etc project to core-parent ](https://github.com/chenyanxu/admin-parent/commit/33c5a228c56fc441d863755b9cd1255559499559)

**Comment by chenyanxu** [comment]
已经通过ConfigManager实现了 应用 模块 菜单的自动注册，根据.cfg配置文件动态编辑
