### ISSUE TITLE
首页--问题：当鼠标放置右侧图标时，没有文字提示该图标的功能。建议加入文字提示功能

### ISSUE THREAD

**Issue by 576226387** [chenyanxu/kalix-parent#320]
![9](https://user-images.githubusercontent.com/22948974/34759219-5d97b93e-f615-11e7-84c5-3635669911b2.png)

**Comment by 576226387** [comment]
![9](https://user-images.githubusercontent.com/22948974/34759228-6bc52730-f615-11e7-9364-3e08887b6258.png)

**Comment by juezhan** [comment]
不会有鼠标操作
