### ISSUE TITLE
办公自动化--业务流程--红头文件申请--预览--问题：文件右下角的时间与当前时间不符

### ISSUE THREAD

**Issue by 576226387** [chenyanxu/kalix-parent#328]
![17](https://user-images.githubusercontent.com/22948974/36716529-8e70b142-1bd5-11e8-9e6c-78284fec002d.png)

**Comment by 576226387** [comment]
出现英文字符
![7](https://user-images.githubusercontent.com/22948974/37263677-263bc72e-25e4-11e8-9b5a-c5004b2db444.png)

**Comment by qingjie1201** [comment]
英文字符设置为空
