### ISSUE TITLE
办公自动化--我的流程--我的流程列表--问题：流程列表默认排序问题。建议：将结束的流程默认排在底部

### ISSUE THREAD

**Issue by 576226387** [chenyanxu/kalix-parent#354]
![37](https://user-images.githubusercontent.com/22948974/36778214-0ed1154e-1ca7-11e8-8d21-1fce405673b0.png)

**Comment by qingjie1201** [comment]
修改我的流程和我参与的流程查询服务，增加默认排序条件（根据流程状态排序，进行中在前，结束在后）

**Comment by qingjie1201** [comment]
然后再次按照开始时间排序
