### ISSUE TITLE
系统应用--权限管理--用户管理--用户查询--问题：查询选项过少，无法快速准确查出目标项

### ISSUE THREAD

**Issue by 576226387** [chenyanxu/kalix-parent#382]
![10](https://user-images.githubusercontent.com/22948974/37439326-93a9c6bc-2832-11e8-819e-23ed6c3256ac.png)

**Comment by qingjie1201** [comment]
新增用户类型、登录名查询条件，修改姓名字段为【姓名/企业名称】
