### ISSUE TITLE
左侧菜单栏收缩变小后，鼠标点击一个悬浮，悬浮菜单被挡住了

### ISSUE THREAD

**Issue by jixuelian** [chenyanxu/kalix-parent#51]
左侧菜单栏收缩变小后，鼠标点击一个悬浮，悬浮菜单被挡住了

**Comment by chenyanxu** [comment]
[Fix navigation bar covered by the dynamic generate component bug.](https://github.com/chenyanxu/framework-parent/commit/db800b069ed18890b5e404c0bb62a52290a58dfa)
