### ISSUE TITLE
计划管理--工作汇报

### ISSUE THREAD

**Issue by jixuelian** [chenyanxu/kalix-parent#54]
新建时，这里的计划类型有问题，计划类型，应该是 个人计划和部门计划，因为汇报也可能对部门计划，另外，这里面计划类型，默认应该是空，可以不针对任何计划 ，进行汇报

**Comment by jixuelian** [comment]
计划类型应该加一个自定义，自定义时关联计划为空

**Comment by paning** [comment]
已处理

**Comment by jixuelian** [comment]
目前选部门计划时，关联计划还是可以为空

**Comment by paning** [comment]
已修改，在计划类型为个人、部门计划时，关联的计划不能为空
同时调整查看工作汇报，在没有关联计划，不显示右侧信息，
