### ISSUE TITLE
【计划管理】-任务关联

### ISSUE THREAD

**Issue by jixuelian** [chenyanxu/kalix-parent#55]
1.目前个人计划、部门计划列表和单个查看中均看不到有和哪些工作汇报和任务关联，应该有着两项
2.目前工作汇报列表和单个查看中均看不到有和哪些工作汇报和任务关联，应该有着两项

**Comment by paning** [comment]
个人计划、部门计划已关联工作汇报
工作汇报已关联个人计划、部门计划

**Comment by zangyanming** [comment]
已解决
