### ISSUE TITLE
【办公自动化】用车申请流程，时间空间显示不全，星期五看不到；必输项没有校验

### ISSUE THREAD

**Issue by jixuelian** [chenyanxu/kalix-parent#81]
【办公自动化】用车申请流程，时间空间显示不全，星期五看不到；必输项没有校验

**Comment by chenyanxu** [comment]
[fix the DateTimePicker can not display all days when the width is to](https://github.com/chenyanxu/framework-parent/commit/77ec8ef7f2f553246574d66c5bc89a48df4e0bb3)
